### PR TITLE
[WIP] bootstrap pyz creator

### PR DESCRIPTION
**Pull request by altendky**
Julian/mkenv#6

### CODE REVIEW

**Comment by altendky** [comment]
@Julian, I think this might be at least far enough along to be worth a look.

**Comment by altendky** [comment]
The pyz is available from the AppVeyor build.

I imagine that after we get to a single entry point with subcommands, that installing would just be a subcommand rather than a separate script.  The pyz could be the full venvs interface and installation would be more like `python venvs-x.y.z.pyz bootstrap`.

**Comment by altendky** [comment]
https://github.com/pypa/virtualenv/blob/master/tasks/make_zipapp.py

**Comment by altendky** [comment]
@Julian, Has shiv been working for you?  I'll put in a PR for a little `mkidr -p` and to build and artifact the shiv env but it's also puking a lot for me.  I guess I'll make this incomplete observation belong here by asking: should I even be working on this PR or is shiv the future of this feature instead?

This is presently broken at least because `zope` is missing an `__init__.py` in the zipapp...  (namespace packages or whatever etc blah)

**Comment by Julian** [comment]
> should I even be working on this PR or is shiv the future of this feature instead?

So basically I want *some* easy single binary being built (which means in theory I don't care how), but I also ideally don't want to maintain any code to build it (which makes me want to lean towards shiv).

If it doesn't work though, "functioning" takes precedence...

I can believe it's puked on you though, I've seen shiv malfunction in the past (and pex malfunction even more)...

But I think we should check to see whether we can get it under control, and if not, then see how small we can make what's needed on top of zipapp to get single binary without maintaining a lot of code... make sense?

**Comment by altendky** [comment]
I'll focus on shiv.  I've got no reason to think it's unsuitable.

**Comment by Julian** [comment]
Cool! Closing this one then I assume?

**Pull request closed without merging**
