### PR TITLE
Use floating virtualenv install

### PR DESCRIPTION
**Pull request by altendky**
#5

### CODE REVIEW

**Comment by altendky** [comment]
This sort of feels like about the quality of spaghetti flung on the wall to see if it sticks...  but it passes tests so maybe it's worth a review.  Then again, it's after midnight.

**Comment by altendky** [comment]
@Julian, I'm not too sure about the last few commits.  They seem like a reasonable use of classes/objects but they also feel possibly counter to your design/style.

**Comment by Julian** [comment]
Oy, I didn't leave anything here, sorry.

I typed out some comments to the effect of "yeah a bit of this looks off but a bit looks on", will have to re-review.

Have you managed to get anything useful out of mkenv yet?

**Comment by altendky** [comment]
Probably not much useful as far as it saving me time. I'm not even sure what made my global envs at this point...  But I've gotten good practice and learned a lot from your feedback.  Thanks so much.  And 'long' term I hope to get this up to snuff for recommending in #python.  I'm tired of explaining how to manually make envs for global installs.  I got a good ways with the bootstrap as well but need to tidy it and get it pushed for you to look at.

**Comment by Julian** [comment]
Hmmm so this patchset confuses me a bit.

Firstly I see what I so far only can think of as an unrelated change, which is the question of -- do `Virtualenv` instances know or not know what filesystem they live on -- in the previous way they didn't, just the path, and so operations that wanted to operate on the filesystem should basically expect to have a filesystem passed in *there*.

Now that doesn't seem like a wonderful choice I suppose, given that paths are not very useful on their own without knowing what they reference, but if we imagine (well it'd potentially be hard for you to imagine :P) that some day `filesystems` grows a way to provide *bound* paths which contain information about what filesystem they intend to live on, then the former model at least makes some sort of sense even logically.

So to me it seems we can choose to make or not make that change independently of the core of #5 -- which, if I understand the patch correctly, this doesn't seem to actually address, does it? Namely, a line like [this one](https://github.com/Julian/venvs/pull/44/files#diff-b51406ca2bb4ff36b797ad0af55e1729R30) is still referencing `sys.executable` to create the virtualenv.

The core of #5 was essentially fairly simple: "vendor in `virtualenv.py` within this package, it's a single file, and then rather than using `python -m virtualenv -p targetpython`, use `targetpython vendoredvirtualenv.py foo`.

Am I missing what this is actually trying to do if not the above?

(And thanks as usual for indulging half baked ideas :)

**Comment by altendky** [comment]
I think the filesystem-as-an-attribute thing was just something that seemed to make more sense given all the passing of the same thing repeatedly.  I suspect that could be peeled out of here.  But yeah, I have to admit that a `Virtualenv` without a filesystem seems kind of useless, or at least not the primary use of the class.

As to `sys.executable`, did per-env Python binary specification get implemented?  If so, or when it does, we can just drop that value in instead of sys.executable, can't we?  The rest of the patch (other than noted above) remains and makes sure we have a copy of virtualenv to use.  I suppose instead of that we could just run the one we already have installed in our own virtualenv.  For some reason, installing to a separate directory felt better to me I guess.  And I hesitate to formally vendor it as that ties it's version to the venvs version installed.

**Comment by altendky** [comment]
If I just drop the interest in a separately installed copy of `virtualenv` and instead use the regular dependency methods to get it installed, also drop the filesystem-as-an-attribute, then this is just replacing...

https://github.com/Julian/venvs/blob/a14e1efc273f288c66725fede1668f9de81ce55c/venvs/common.py#L14-L21

with this?

```python
import virtualenv

subprocess.check_call(
    [
        sys.executable,
        virtualenv.__file__,
        "--quiet",
    ] + list(arguments) + [str(virtualenv.path)],
    stderr=stderr,
)
```

Or perhaps a non-importing option of getting that same path (py2: imp something and py3: importlib something maybe).

Also, isn't #5 solved (for now) by way of https://github.com/Julian/venvs/pull/43/files?  When #15 gets us multiple python binaries to deal with then we'll have to have something more...  like above maybe (with `sys.executable` being replaced by whatever #15's solution introduces).

**Comment by altendky** [comment]
First pass at a non-importing `virtualenv.py` finder.

https://repl.it/@altendky/23-find-not-imported-module-path-py2
https://repl.it/@altendky/23-find-not-imported-module-path-py3
```python
import sys

def get_module_path(name):
    if sys.version_info >= (3, 4):
        import importlib
        spec = importlib.util.find_spec(name)
        path = spec.origin
    else:
        import imp
        f, path, _ = imp.find_module(name)
        f.close()

    return path

print(get_module_path('virtualenv'))
```
```
/home/runner/.site-packages/virtualenv.py
```

**Comment by altendky** [comment]
I think the basic issue is that neither of us care (anymore in my case) about having a 'floating' copy of virtualenv which is what this mostly did (hence the PR title).  So I think we can drop this.  I'm submitting another PR that takes a step closer to running virtualenv directly from the target python executable (#5 / #15 related but not really either directly since the former is already completed I think and, well, it only preps for the latter).

**Pull request closed without merging**
