### PR TITLE
Shiv cleanup and addition to build

### PR DESCRIPTION
**Pull request by altendky**

### CODE REVIEW

**Comment by altendky** [comment]
I'm still having troubles getting venvs to work for me but this piece seems better.

**Comment by Julian** [comment]
Woohoo, thanks! I meant to do this myself but glad you beat me to it.

I actually haven't tried using shiv on venvs again recently, so I don't know if it works or not :), but yeah let's see.

And your troubles are getting this working in a single binary, or in general :/?

**Comment by altendky** [comment]
In general not working... I'll have to make up a real report.  I'm seeing errors referencing venvs 3.1 and it doesn't install venvs in the env I asked it to (it does create a symlink...).   Hmm, I wonder if this is the same ol' no-src/-issue.  Anyways, I'll follow up separately when I get a chance.

**Comment by Julian** [comment]
Huh, that's definitely odd, I've been using it on many machines but yeah
lemme know what you're running, would definitely want to fix that.

**Comment by altendky** [comment]
Yep, lack of src/.  I was in the git repo root and had -e installed venvs thus having venvs.egg-info/ in cwd.  Installing without -e fixed it.

```
 ⚙  ~/r/venvs   master  venv/bin/pip install .; rm -rf ~/.local/share/virtualenvs/venvs; venv/bin/venvs converge; ll ~/.local/share/virtualenvs/venvs/bin
Processing /home/altendky/repos/venvs
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: tomlkit in ./venv/lib/python3.8/site-packages (from venvs==3.1.1.dev205+gfbd00d7) (0.5.8)
Requirement already satisfied: appdirs in ./venv/lib/python3.8/site-packages (from venvs==3.1.1.dev205+gfbd00d7) (1.4.3)
Requirement already satisfied: filesystems>=0.23.0 in ./venv/lib/python3.8/site-packages (from venvs==3.1.1.dev205+gfbd00d7) (0.23.0)
Requirement already satisfied: attrs>=19.2.0 in ./venv/lib/python3.8/site-packages (from venvs==3.1.1.dev205+gfbd00d7) (19.3.0)
Requirement already satisfied: click in ./venv/lib/python3.8/site-packages (from venvs==3.1.1.dev205+gfbd00d7) (7.0)
Requirement already satisfied: pyrsistent in ./venv/lib/python3.8/site-packages (from venvs==3.1.1.dev205+gfbd00d7) (0.15.6)
Requirement already satisfied: virtualenv in ./venv/lib/python3.8/site-packages (from venvs==3.1.1.dev205+gfbd00d7) (16.7.9)
Requirement already satisfied: toml>=0.10.0 in ./venv/lib/python3.8/site-packages (from venvs==3.1.1.dev205+gfbd00d7) (0.10.0)
Requirement already satisfied: tqdm in ./venv/lib/python3.8/site-packages (from venvs==3.1.1.dev205+gfbd00d7) (4.41.0)
Requirement already satisfied: packaging in ./venv/lib/python3.8/site-packages (from venvs==3.1.1.dev205+gfbd00d7) (19.2)
Requirement already satisfied: zope.interface in ./venv/lib/python3.8/site-packages (from filesystems>=0.23.0->venvs==3.1.1.dev205+gfbd00d7) (4.7.1)
Requirement already satisfied: six in ./venv/lib/python3.8/site-packages (from pyrsistent->venvs==3.1.1.dev205+gfbd00d7) (1.13.0)
Requirement already satisfied: pyparsing>=2.0.2 in ./venv/lib/python3.8/site-packages (from packaging->venvs==3.1.1.dev205+gfbd00d7) (2.4.6)
Requirement already satisfied: setuptools in ./venv/lib/python3.8/site-packages (from zope.interface->filesystems>=0.23.0->venvs==3.1.1.dev205+gfbd00d7) (42.0.2)
Building wheels for collected packages: venvs
  Building wheel for venvs (PEP 517) ... done
  Created wheel for venvs: filename=venvs-3.1.1.dev205+gfbd00d7-cp38-none-any.whl size=25131 sha256=725ece73834512cc4a60cf6c150915f996393063981f07f2e6327e8f0c513360
  Stored in directory: /tmp/pip-ephem-wheel-cache-g_dwtdnl/wheels/f8/cb/45/4f712b435dbc21d2a69a0d7f669abc1f9a750a320afa8e84be
Successfully built venvs
Installing collected packages: venvs
  Found existing installation: venvs 3.1.1.dev205+gfbd00d7
    Uninstalling venvs-3.1.1.dev205+gfbd00d7:
      Successfully uninstalled venvs-3.1.1.dev205+gfbd00d7
Successfully installed venvs-3.1.1.dev205+gfbd00d7
twine: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:15<00:00,  5.05s/venv]
total 20M
-rw-rw-r-- 1 altendky altendky 2.2K Dec 29 10:15 activate
-rw-rw-r-- 1 altendky altendky 1.5K Dec 29 10:15 activate.csh
-rw-rw-r-- 1 altendky altendky 3.1K Dec 29 10:15 activate.fish
-rw-rw-r-- 1 altendky altendky 1.8K Dec 29 10:15 activate.ps1
-rw-rw-r-- 1 altendky altendky 1.5K Dec 29 10:15 activate_this.py
-rw-rw-r-- 1 altendky altendky 1.2K Dec 29 10:15 activate.xsh
-rwxrwxr-x 1 altendky altendky  273 Dec 29 10:15 easy_install*
-rwxrwxr-x 1 altendky altendky  273 Dec 29 10:15 easy_install-3.8*
-rwxrwxr-x 1 altendky altendky  260 Dec 29 10:15 pip*
-rwxrwxr-x 1 altendky altendky  260 Dec 29 10:15 pip3*
-rwxrwxr-x 1 altendky altendky  260 Dec 29 10:15 pip3.8*
lrwxrwxrwx 1 altendky altendky    9 Dec 29 10:15 python -> python3.8*
lrwxrwxrwx 1 altendky altendky    9 Dec 29 10:15 python3 -> python3.8*
-rwxrwxr-x 1 altendky altendky  20M Dec 29 10:15 python3.8*
-rwxrwxr-x 1 altendky altendky 2.4K Dec 29 10:15 python-config*
-rwxrwxr-x 1 altendky altendky  247 Dec 29 10:15 tqdm*
-rwxrwxr-x 1 altendky altendky  249 Dec 29 10:15 venvs*
-rwxrwxr-x 1 altendky altendky  249 Dec 29 10:15 virtualenv*
-rwxrwxr-x 1 altendky altendky  251 Dec 29 10:15 wheel*
```
```
 ⚙  ~/r/venvs   master  venv/bin/pip install -e .; rm -rf ~/.local/share/virtualenvs/venvs; venv/bin/venvs converge; ll ~/.local/share/virtualenvs/venvs/bin
Obtaining file:///home/altendky/repos/venvs
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: pyrsistent in ./venv/lib/python3.8/site-packages (from venvs==3.1.1.dev205+gfbd00d7) (0.15.6)
Requirement already satisfied: packaging in ./venv/lib/python3.8/site-packages (from venvs==3.1.1.dev205+gfbd00d7) (19.2)
Requirement already satisfied: attrs>=19.2.0 in ./venv/lib/python3.8/site-packages (from venvs==3.1.1.dev205+gfbd00d7) (19.3.0)
Requirement already satisfied: toml>=0.10.0 in ./venv/lib/python3.8/site-packages (from venvs==3.1.1.dev205+gfbd00d7) (0.10.0)
Requirement already satisfied: appdirs in ./venv/lib/python3.8/site-packages (from venvs==3.1.1.dev205+gfbd00d7) (1.4.3)
Requirement already satisfied: filesystems>=0.23.0 in ./venv/lib/python3.8/site-packages (from venvs==3.1.1.dev205+gfbd00d7) (0.23.0)
Requirement already satisfied: tqdm in ./venv/lib/python3.8/site-packages (from venvs==3.1.1.dev205+gfbd00d7) (4.41.0)
Requirement already satisfied: virtualenv in ./venv/lib/python3.8/site-packages (from venvs==3.1.1.dev205+gfbd00d7) (16.7.9)
Requirement already satisfied: tomlkit in ./venv/lib/python3.8/site-packages (from venvs==3.1.1.dev205+gfbd00d7) (0.5.8)
Requirement already satisfied: click in ./venv/lib/python3.8/site-packages (from venvs==3.1.1.dev205+gfbd00d7) (7.0)
Requirement already satisfied: six in ./venv/lib/python3.8/site-packages (from pyrsistent->venvs==3.1.1.dev205+gfbd00d7) (1.13.0)
Requirement already satisfied: pyparsing>=2.0.2 in ./venv/lib/python3.8/site-packages (from packaging->venvs==3.1.1.dev205+gfbd00d7) (2.4.6)
Requirement already satisfied: zope.interface in ./venv/lib/python3.8/site-packages (from filesystems>=0.23.0->venvs==3.1.1.dev205+gfbd00d7) (4.7.1)
Requirement already satisfied: setuptools in ./venv/lib/python3.8/site-packages (from zope.interface->filesystems>=0.23.0->venvs==3.1.1.dev205+gfbd00d7) (42.0.2)
Installing collected packages: venvs
  Found existing installation: venvs 3.1.1.dev205+gfbd00d7
    Uninstalling venvs-3.1.1.dev205+gfbd00d7:
      Successfully uninstalled venvs-3.1.1.dev205+gfbd00d7
  Running setup.py develop for venvs
Successfully installed venvs
tox:  33%|████████████████████████████████████████████████████████                                                                                                                | 1/3 [00:04<00:09,  4.68s/venv]ERROR: venvs 3.1.1.dev205+gfbd00d7 requires appdirs, which is not installed.
ERROR: venvs 3.1.1.dev205+gfbd00d7 requires attrs>=19.2.0, which is not installed.
ERROR: venvs 3.1.1.dev205+gfbd00d7 requires click, which is not installed.
ERROR: venvs 3.1.1.dev205+gfbd00d7 requires filesystems>=0.23.0, which is not installed.
ERROR: venvs 3.1.1.dev205+gfbd00d7 requires pyrsistent, which is not installed.
ERROR: venvs 3.1.1.dev205+gfbd00d7 requires tomlkit, which is not installed.
ERROR: venvs 3.1.1.dev205+gfbd00d7 requires tqdm, which is not installed.
twine:  67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                       | 2/3 [00:08<00:04,  4.56s/venv]ERROR: venvs 3.1.1.dev205+gfbd00d7 requires appdirs, which is not installed.
ERROR: venvs 3.1.1.dev205+gfbd00d7 requires attrs>=19.2.0, which is not installed.
ERROR: venvs 3.1.1.dev205+gfbd00d7 requires click, which is not installed.
ERROR: venvs 3.1.1.dev205+gfbd00d7 requires filesystems>=0.23.0, which is not installed.
ERROR: venvs 3.1.1.dev205+gfbd00d7 requires packaging, which is not installed.
ERROR: venvs 3.1.1.dev205+gfbd00d7 requires pyrsistent, which is not installed.
ERROR: venvs 3.1.1.dev205+gfbd00d7 requires toml>=0.10.0, which is not installed.
ERROR: venvs 3.1.1.dev205+gfbd00d7 requires tomlkit, which is not installed.
ERROR: venvs 3.1.1.dev205+gfbd00d7 requires virtualenv, which is not installed.
twine: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:15<00:00,  5.15s/venv]
total 20M
-rw-rw-r-- 1 altendky altendky 2.2K Dec 29 10:16 activate
-rw-rw-r-- 1 altendky altendky 1.5K Dec 29 10:16 activate.csh
-rw-rw-r-- 1 altendky altendky 3.1K Dec 29 10:16 activate.fish
-rw-rw-r-- 1 altendky altendky 1.8K Dec 29 10:16 activate.ps1
-rw-rw-r-- 1 altendky altendky 1.5K Dec 29 10:16 activate_this.py
-rw-rw-r-- 1 altendky altendky 1.2K Dec 29 10:16 activate.xsh
-rwxrwxr-x 1 altendky altendky  273 Dec 29 10:16 easy_install*
-rwxrwxr-x 1 altendky altendky  273 Dec 29 10:16 easy_install-3.8*
-rwxrwxr-x 1 altendky altendky  260 Dec 29 10:16 pip*
-rwxrwxr-x 1 altendky altendky  260 Dec 29 10:16 pip3*
-rwxrwxr-x 1 altendky altendky  260 Dec 29 10:16 pip3.8*
lrwxrwxrwx 1 altendky altendky    9 Dec 29 10:16 python -> python3.8*
lrwxrwxrwx 1 altendky altendky    9 Dec 29 10:16 python3 -> python3.8*
-rwxrwxr-x 1 altendky altendky  20M Dec 29 10:16 python3.8*
-rwxrwxr-x 1 altendky altendky 2.4K Dec 29 10:16 python-config*
-rwxrwxr-x 1 altendky altendky  247 Dec 29 10:16 tqdm*
-rwxrwxr-x 1 altendky altendky  249 Dec 29 10:16 virtualenv*
-rwxrwxr-x 1 altendky altendky  251 Dec 29 10:16 wheel*
```
Note the missing venvs executable.  Python looks in the cwd and notes the egg info and considers that stuff 'installed' so it doesn't install a new copy of venvs.  I'm guessing the v3.1.1 misversion is coming from me having clone my repo and not properly gotten tags from yours shoved into it...  or something.  Someday I'll remember to not sit in the project root...

**Comment by Julian** [comment]
Are you sure that's src related? pip just doesn't create scripts whenever
you already have an installed package, regardless, AFAIK.

**Comment by altendky** [comment]
But why does some other env think that venvs is installed already?  Or what else is going on?  I'm trying to do a 'manual' recreation.

**Comment by Julian** [comment]
*If* this is the same (other secondary) issue, which I think it is but I didn't think about it carefully, pip gets horribly confused if you have an `.egg-info` directory (these days? it's hard to know whether it's a new bug, I've discussed it with some PyPA folks randomly at PyCon but yeah I never spent time to investigate) even if the egg-info directory is for some totally unrelated venv. In exactly which circumstances and versions yeah did not yet narrow things down, but if you do manage to reproduce lemme know, I just doubt it would be any different with src, it's purely a setuptools egg-info issue AFAIK.

They're going to (hopefully?) reinvent -e into a better thing soon anyhow *fingers crossed*.

**Comment by altendky** [comment]
Away from my computer so I can't confirm but as I recall src/ would move the egg info into src/.  Then it isn't in cwd.  But sure, I consider src/ to be compensation for python misfeatures (or maybe sometimes bugs).  If python didn't search cwd, I probably wouldn't src/.  It's a purely pragmatic thing I switched to after being bit a few times.

**Pull request merged**
